name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force || true

      - name: Run tests
        run: |
          npm ci
          npm run test
          npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: 'chore(deps): automated dependency updates'
          body: |
            ## 🔄 Automated Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### Changes
            - Updated npm dependencies to latest compatible versions
            - Applied security fixes via `npm audit fix`
            
            ### Testing
            - ✅ All tests pass
            - ✅ Build successful
            
            This PR was automatically created by the dependency update workflow.
          branch: chore/dependency-updates
          delete-branch: true
          base: main
